language: php

dist: trusty

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  
matrix:
  fast_finish: true

before_script:
  - composer install --prefer-source --no-interaction;

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

