language: php

dist: trusty

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  
matrix:
  fast_finish: true

before_script:
  - composer update;

script:
  - vendor/bin/phpunit;

notifications:
  email: false

